name: publish pab
on:
  push:
    branches:
      - master
      - workflows
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install
      - name: Run Test
        run: poetry run pytest
