name: publish pab
on:
  push:
    branches:
      - master
      - workflows
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3.1.0
      - name: Install Poetry
        run: pip install poetry
      - name: test
        run: pip install lbry-rocksdb-optimized
      - name: Install Dependencies
        run: poetry install
      - name: Run Test
        run: pytest
      
